import './src/styles/style.css'
import './src/script/components/app-bar.js'
import './src/script/components/hero-section'
import './src/script/components/content-section'
import './src/script/components/slide-over'
import './src/script/components/footer'
